using System.Text.Json;
using TraceHelix.Domain.Analysis;
using TraceHelix.Domain.Traces;
using TraceHelix.Infrastructure.Detection;
using Xunit;
namespace TraceHelix.Infrastructure.Tests.Detection;

public sealed class AllDetectorBehaviorTests
{
    private static TraceEvent E(long n, TraceEventKind kind, string summary, string hash = "hash") { var id = Guid.NewGuid(); return new(id, Guid.NewGuid(), n, DateTimeOffset.UnixEpoch.AddSeconds(n), kind, "agent", summary, JsonDocument.Parse("{}").RootElement, new SourceReference("generic-jsonl", "input", "x", n, n is < int.MaxValue ? (int)n + 1 : null, "/"), [], hash); }
    private static StepClassification C(TraceEvent e, StepLabel label) => new(e.Id, label, .8f, "rules", "1.0", [e.Id], null);
    [Fact] public async Task Each_detector_emits_versioned_evidence_at_threshold() { var repeated = new[] { E(0, TraceEventKind.ToolCall, "read"), E(1, TraceEventKind.ToolCall, "read"), E(2, TraceEventKind.ToolCall, "read") }; var plans = new[] { E(0, TraceEventKind.Reasoning, "plan", "a"), E(1, TraceEventKind.Reasoning, "plan", "b"), E(2, TraceEventKind.Reasoning, "plan", "c") }; var gap = new[] { E(0, TraceEventKind.FileChange, "write", "a"), E(1, TraceEventKind.Status, "success", "b") }; var early = new[] { E(0, TraceEventKind.Status, "success", "a"), E(1, TraceEventKind.Error, "failed", "b") }; var recovery = new[] { E(0, TraceEventKind.Error, "retry", "a"), E(1, TraceEventKind.Error, "retry", "b"), E(2, TraceEventKind.Error, "retry", "c") }; var cases = new (IReadOnlyList<TraceEvent>, IReadOnlyList<StepClassification>)[] { (repeated, repeated.Select(x => C(x, StepLabel.Explore)).ToArray()), (plans, plans.Select(x => C(x, StepLabel.Plan)).ToArray()), (gap, [C(gap[0], StepLabel.Execute), C(gap[1], StepLabel.Unknown)]), (early, early.Select(x => C(x, StepLabel.Unknown)).ToArray()), (recovery, recovery.Select(x => C(x, StepLabel.Recover)).ToArray()), (recovery, recovery.Select(x => C(x, StepLabel.Recover)).ToArray()) }; var detectors = DefaultDetectors.Create(); for (var i = 0; i < detectors.Count; i++) { var alerts = await detectors[i].DetectAsync(cases[i].Item1, cases[i].Item2, TestContext.Current.CancellationToken); var alert = Assert.Single(alerts); Assert.Equal(detectors[i].Code, alert.Code); Assert.Equal("1.0.0", alert.DetectorVersion); Assert.NotEmpty(alert.Parameters); Assert.NotEmpty(alert.EvidenceEventIds); Assert.Contains("Observed", alert.Explanation, StringComparison.Ordinal); } }
    [Fact] public async Task Empty_input_and_below_threshold_do_not_alert() { var two = new[] { E(0, TraceEventKind.Message, "plan", "a"), E(1, TraceEventKind.Message, "plan", "b") }; var classifications = two.Select(x => C(x, StepLabel.Plan)).ToArray(); foreach (var detector in DefaultDetectors.Create()) { Assert.Empty(await detector.DetectAsync([], [], TestContext.Current.CancellationToken)); } Assert.Empty(await DefaultDetectors.Create()[1].DetectAsync(two, classifications, TestContext.Current.CancellationToken)); Assert.Empty(await DefaultDetectors.Create()[4].DetectAsync(two, two.Select(x => C(x, StepLabel.Recover)).ToArray(), TestContext.Current.CancellationToken)); Assert.Empty(await DefaultDetectors.Create()[5].DetectAsync(two, [], TestContext.Current.CancellationToken)); }
}
